//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eventBitTestClient.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntFacility
    {
        public int FacilityID { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Fax { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string PostalCode { get; set; }
        public string State { get; set; }
        public string sysChangeHashB64 { get; set; }
        public string sysColumnSigB64 { get; set; }
        public int sysEventID { get; set; }
        public Nullable<double> sysInsertDateEpoch { get; set; }
        public string sysInsertedBy { get; set; }
        public Nullable<double> sysRowStampNum { get; set; }
        public string sysRowState { get; set; }
        public Nullable<int> sysSyncEnterpriseID { get; set; }
        public Nullable<double> sysUpdateDateEpoch { get; set; }
        public string sysUpdatedBy { get; set; }
    }
}
