//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eventBitTestClient.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityState
    {
        public string EntityID { get; set; }
        public string ShowCode { get; set; }
        public Nullable<double> sysRowStampNumMax { get; set; }
        public Nullable<double> sysEventId { get; set; }
    }
}
