//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eventBitTestClient.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntPerson
    {
        public long PersonID { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string BadgeID { get; set; }
        public string Bio { get; set; }
        public string City { get; set; }
        public string Company { get; set; }
        public string Company2 { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Facebook { get; set; }
        public string Fax { get; set; }
        public string FirstName { get; set; }
        public Nullable<bool> IsAttendee { get; set; }
        public Nullable<bool> IsContact { get; set; }
        public Nullable<bool> IsExhibitor { get; set; }
        public Nullable<bool> IsMember { get; set; }
        public Nullable<bool> IsSpeaker { get; set; }
        public Nullable<bool> IsSponsor { get; set; }
        public string LastName { get; set; }
        public string LinkedIn { get; set; }
        public string MemberNumber { get; set; }
        public string MemberType { get; set; }
        public string Middle { get; set; }
        public string Mobile { get; set; }
        public string NickName { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string PostalCode { get; set; }
        public string Prefix { get; set; }
        public string State { get; set; }
        public string Suffix { get; set; }
        public string sysChangeHashB64 { get; set; }
        public string sysColumnSigB64 { get; set; }
        public int sysEventID { get; set; }
        public Nullable<double> sysInsertDateEpoch { get; set; }
        public string sysInsertedBy { get; set; }
        public Nullable<double> sysRowStampNum { get; set; }
        public string sysRowState { get; set; }
        public Nullable<int> sysSyncEnterpriseID { get; set; }
        public Nullable<double> sysUpdateDateEpoch { get; set; }
        public string sysUpdatedBy { get; set; }
    }
}
