//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eventBitTestClient.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntPersonRegistration
    {
        public long PersonRegistrationID { get; set; }
        public Nullable<double> CancelDateEpoch { get; set; }
        public string CancelType { get; set; }
        public Nullable<long> PersonID { get; set; }
        public Nullable<double> RegistrationDateEpoch { get; set; }
        public string RegistrationTypeCode { get; set; }
        public string RegistrationTypeDescription { get; set; }
        public string SourceCode { get; set; }
        public string sysChangeHashB64 { get; set; }
        public string sysColumnSigB64 { get; set; }
        public int sysEventID { get; set; }
        public Nullable<double> sysInsertDateEpoch { get; set; }
        public string sysInsertedBy { get; set; }
        public Nullable<double> sysRowStampNum { get; set; }
        public string sysRowState { get; set; }
        public Nullable<int> sysSyncEnterpriseID { get; set; }
        public Nullable<double> sysUpdateDateEpoch { get; set; }
        public string sysUpdatedBy { get; set; }
    }
}
