//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eventBitTestClient.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eventBitEntities : DbContext
    {
        public eventBitEntities()
            : base("name=eventBitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SnapshotLog> SnapshotLogs { get; set; }
        public virtual DbSet<EntityState> EntityStates { get; set; }
        public virtual DbSet<EntBooth> EntBooths { get; set; }
        public virtual DbSet<EntCategory> EntCategories { get; set; }
        public virtual DbSet<EntCompany> EntCompanies { get; set; }
        public virtual DbSet<EntCompanyAltName> EntCompanyAltNames { get; set; }
        public virtual DbSet<EntCompanyBooth> EntCompanyBooths { get; set; }
        public virtual DbSet<EntCompanyCategory> EntCompanyCategories { get; set; }
        public virtual DbSet<EntFacility> EntFacilities { get; set; }
        public virtual DbSet<EntFieldDetail> EntFieldDetails { get; set; }
        public virtual DbSet<EntFieldDetailPick> EntFieldDetailPicks { get; set; }
        public virtual DbSet<EntLocation> EntLocations { get; set; }
        public virtual DbSet<EntLocationProduct> EntLocationProducts { get; set; }
        public virtual DbSet<EntLocationSchedule> EntLocationSchedules { get; set; }
        public virtual DbSet<EntMap> EntMaps { get; set; }
        public virtual DbSet<EntMapBooth> EntMapBooths { get; set; }
        public virtual DbSet<EntPerson> EntPersons { get; set; }
    }
}
